### ISSUE TITLE
What does spp mean?

### ISSUE THREAD

**Issue by zhangshenxing** [SpaceBang/SppAdvancementsMaker#1]

**Comment by SPGoding** [comment]
SPGoding’s Programs
根据Upper Cammel命名规则，SPGoding由SP、Goding两词组成，取第一词SP作为本人名字简称。故缩写为SPP。再次根据Upper Cammel命名规则，S大写，pp小写，故为Spp

**Comment by zhangshenxing** [comment]
海星…本来我是准备做26个原版模组的🌝
